server:
  port: 8081

spring:
  profiles:
    include: secret
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1
    open-in-view: true


# db
logging.level.org.hibernate.SQL: debug
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.hibernate.ddl-auto: update

spring.datasource.url: jdbc:h2:mem:testdb
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
spring.datasource.password:
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect